Repository exercism/typescript, pull requests merged in 2021-04, with the labels that each got.

#410 🤖 Add file patterns to config.json
  config.json
Labels: v3-migration 🤖

#426 Update packages for root and common package.json
  .github/dependabot.yml
Labels: chore :wrench:, security :rotating_light:

#425 [GHA] Rename GHA action to be consistent with open PR and JavaScript track
  .github/workflows/action-format.yml
Labels: chore :wrench:

#424 [GHA] Add codeQL
  .github/workflows/codeql.yml
Labels: chore :wrench:

#423 [GHA] Pin GitHub Actions actions
  .github/workflows/pr.ci.js.yml
  .github/workflows/verify-code-formatting.yml
Labels: chore :wrench:

#422 [GHA] Add /sync action
  .github/workflows/action-sync.yml
Labels: chore :wrench:

#421 [GHA] Pin Github Action in configlet workflow
  .github/workflows/configlet.yml
Labels: chore :wrench:

#420 [GHA] Update CI script to use main branch instead of master
  .github/workflows/ci.js.yml
Labels: chore :wrench:

#439 Updated online editor code style #394
  config.json
Labels: reputation/contributed_code/minor

#449 Update yarn.lock for common packages
  common/yarn.lock
Labels: chore :wrench:, reputation/contributed_code/minor

#438 401/status
  config.json
Labels: reputation/contributed_code/minor

#451 Update CONTRIBUTING so people can use it again
  CONTRIBUTING.md
  reference/implementing-a-concept-exercise.md
Labels: documentation :book:, v3-migration 🤖

#453 Pass all the linting
  .eslintrc
  exercises/practice/crypto-square/.meta/proof.ci.ts
  exercises/practice/diffie-hellman/.meta/proof.ci.ts
  exercises/practice/grade-school/.meta/proof.ci.ts
  exercises/practice/largest-series-product/.meta/proof.ci.ts
  exercises/practice/list-ops/.docs/instructions.append.md
  exercises/practice/list-ops/.meta/proof.ci.ts
  exercises/practice/list-ops/list-ops.test.ts
  exercises/practice/list-ops/list-ops.ts
  exercises/practice/matching-brackets/.meta/proof.ci.ts
  exercises/practice/palindrome-products/.meta/proof.ci.ts
  exercises/practice/palindrome-products/palindrome-products.test.ts
  exercises/practice/phone-number/.meta/proof.ci.ts
  exercises/practice/protein-translation/.meta/proof.ci.ts
  exercises/practice/pythagorean-triplet/.meta/proof.ci.ts
  exercises/practice/pythagorean-triplet/pythagorean-triplet.test.ts
  exercises/practice/queen-attack/.meta/proof.ci.ts
  exercises/practice/resistor-color-duo/.meta/proof.ci.ts
  exercises/practice/robot-simulator/.meta/proof.ci.ts
  exercises/practice/robot-simulator/robot-simulator.test.ts
  exercises/practice/robot-simulator/robot-simulator.ts
  exercises/practice/secret-handshake/.meta/proof.ci.ts
  exercises/practice/series/.meta/proof.ci.ts
  exercises/practice/space-age/.meta/proof.ci.ts
  exercises/practice/sum-of-multiples/.meta/proof.ci.ts
  exercises/practice/triangle/.meta/proof.ci.ts
  exercises/practice/wordy/.meta/proof.ci.ts
Labels: chore :wrench:, ci :gear:, reputation/contributed_code/major

#454 Update README.md
  README.md
Labels: documentation :book:

#492 🤖 Add Ace editor and highlightjs languages to config.json
  config.json
Labels: v3-migration 🤖
